# anisble_openssh
- name: OpenSSH | (Debian) Make sure server and client packages are installed
  when: ansible_os_family == "Debian"
  apt: pkg={{ item }} state=present
  with_items:
    - "openssh-client"
    - "openssh-server"

- name: OpenSSH | Seting up service name
  set_fact: openssh_service_name=ssh
    
- name: OpenSSH | Configure OpenSSH Client
  template:
    src: etc_ssh_ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644

- name: OpenSSH | Configure OpenSSH Server
  template:
    src: etc_ssh_sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ssh