# anisble_openssh/tasks/redhat.yml
- name: OpenSSH | (RedHat) Make sure server and client packages are installed
  yum: pkg={{ item }} state=present
  with_items: 
    - "openssh-clients"
    - "openssh-server"

- name: OpenSSH | Setting FACT up service name
  set_fact: openssh_service_name=sshd
    
- name: OpenSSH | Configure OpenSSH Client
  template:
    src: etc_ssh_ssh_config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644

- name: OpenSSH | Configure OpenSSH Server
  template:
    src: etc_ssh_sshd_config_RedHat.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ssh